# Generated by Django 4.2.5 on 2023-10-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailingsettings_recipients_alter_client_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='status',
            field=models.BooleanField(default=False, verbose_name='статус отправки'),
        ),
    ]
