# Generated by Django 4.2.5 on 2023-10-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailinglog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingmessage',
            name='body',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='mailingmessage',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Тема сообщения'),
        ),
    ]
